### ISSUE TITLE
Adding a proper .gitignore file

### ISSUE THREAD

**Issue by kritikaparmar-programmer** [chandrikadeb7/Face-Mask-Detection#106]
## 🚀 Feature
I want to add a proper .gitignore file
## Motivation
some files like .vscode and virtual environments other than venv are getting tracked right now.
## Pitch
I'll add a proper .gitignore file.

**Comment by kritikaparmar-programmer** [comment]
Hey, @chandrikadeb7 please assign me this.

**Comment by smriti1313** [comment]
Hi If there's a chance of me working then i would if you could assign this to me. Thanks.
