### ISSUE TITLE
Use case

### ISSUE THREAD

**Issue by NKKFu** [chandrikadeb7/Face-Mask-Detection#11]
Hello, I am a beginner web developer and I would love to create a project similar to yours.

However, because I'm a beginner, I don't know if the MIT license allows me to copy your software or if I need additional permission or something else.

If I can make a copy of your source code, do I need to include thanks, pay for something, or anything else?

Thank you :)

**Comment by lakshaychhabra** [comment]
It means She is not liable if code fails or something else happens because of the code. You can copy the source code, your choice to include thanks for respect.
