### ISSUE TITLE
Add the links in Readme where this repo is cited in research papers 

### ISSUE THREAD

**Issue by chandrikadeb7** [chandrikadeb7/Face-Mask-Detection#112]
## 📚 Documentation

Search for the citations given to this repository in Google Scholar etc. and add the links in the Readme under Cited By section (new)

**Comment by samratkumardey** [comment]
The following research article cited this repository with proper permission by the Author
https://link.springer.com/chapter/10.1007%2F978-981-33-4673-4_49

**Comment by kanishkaa24** [comment]
Hey! Can I work on this issue?

**Comment by kanishkaa24** [comment]
Hey, I could find these
https://reposhub.com/python/deep-learning/chandrikadeb7-Face-Mask-Detection.html
https://rahul-maheshmaheshwari.medium.com/real-time-face-and-mask-on-off-detection-aec80b7920cc
https://www.covid19dataindex.org/details?id=1371
https://site-1172855.mozfiles.com/files/1172855/94878716588.pdf
Please tell me if they are fine.

**Comment by chandrikadeb7** [comment]
> Hey, I could find these
> https://reposhub.com/python/deep-learning/chandrikadeb7-Face-Mask-Detection.html
> https://rahul-maheshmaheshwari.medium.com/real-time-face-and-mask-on-off-detection-aec80b7920cc
> https://www.covid19dataindex.org/details?id=1371
> https://site-1172855.mozfiles.com/files/1172855/94878716588.pdf
> Please tell me if they are fine.

Search in Google Scholar for references in research papers

**Comment by anirudhsai20** [comment]
Hi @chandrikadeb7 . Can I please work on this under DWOC?

**Comment by chandrikadeb7** [comment]
> Hi @chandrikadeb7 . Can I please work on this under DWOC?

Proceed!
