### ISSUE TITLE
project logo creation 

### ISSUE THREAD

**Issue by divyasri77** [chandrikadeb7/Face-Mask-Detection#113]
## 🚀 Feature

It has no logo in the project list page

## Motivation

To bring a catchy outline

## Pitch

If we add a logo it will be catchy for the contributors

**Comment by chandrikadeb7** [comment]
Hello @divyasri77 Are you contributing as part of DWOC?

**Comment by divyasri77** [comment]
> Hello @divyasri77 Are you contributing as part of DWOC?

yes

**Comment by divyasri77** [comment]
Can I create a logo

**Comment by chandrikadeb7** [comment]
> Can I create a logo

Proceed!

**Comment by divyasri77** [comment]
![Face MaSK DETECTION](https://user-images.githubusercontent.com/68841372/107841983-cc739f80-6de5-11eb-8e14-60a290d098bf.png)
check this

**Comment by kanishkaa24** [comment]
Hey! Can I work on this issue ?

**Comment by Vrushti24** [comment]
Hey is still this issue open ..?? @chandrikadeb7 I want to work on this

**Comment by chandrikadeb7** [comment]
> Hey! Can I work on this issue ?

Design your logo and paste here, I will approve the best one.

**Comment by chandrikadeb7** [comment]
> Hey is still this issue open ..?? @chandrikadeb7 I want to work on this

Design your logo and paste here, I will approve the best one.

**Comment by kanishkaa24** [comment]
![Face Mask Detection](https://user-images.githubusercontent.com/71253790/108358046-40fa7400-7214-11eb-93ec-24a4cf1a08d4.png)
@chandrikadeb7 Mam I have designed this.

**Comment by Vrushti24** [comment]
![facemaskdetection ai @ 51 06% (CMYK_GPU Preview)  18-02-2021 18_33_18](https://user-images.githubusercontent.com/71961160/108361037-fda20480-7217-11eb-8788-e0009e13905a.png)
@chandrikadeb7  I have tried this one if u need changes do let me know

**Comment by chandrikadeb7** [comment]
> ![facemaskdetection ai @ 51 06% (CMYK_GPU Preview) 18-02-2021 18_33_18](https://user-images.githubusercontent.com/71961160/108361037-fda20480-7217-11eb-8788-e0009e13905a.png)
> @chandrikadeb7 I have tried this one if u need changes do let me know

I like this one, we can proceed with this. Please make a PR

**Comment by Vrushti24** [comment]
@chandrikadeb7 I'm glad u like it I will make PR right now thank you

**Comment by Vrushti24** [comment]
@chandrikadeb7 added PR #118
