### ISSUE TITLE
Tensorflow issue on raspberry pi

### ISSUE THREAD

**Issue by vinamramunot-tech** [chandrikadeb7/Face-Mask-Detection#117]
## 🐛 Bug Report

#44 I found the solution to run this face mask detection repo on raspberry pi that has raspbian 32-bit as the operating system. I wanted to ask if you would like this solution to be documented.

**Comment by chandrikadeb7** [comment]
> ## 🐛 Bug Report
> #44 I found the solution to run this face mask detection repo on raspberry pi that has raspbian 32-bit as the operating system. I wanted to ask if you would like this solution to be documented.

Sure, you can document the solution!

**Comment by vinamramunot-tech** [comment]
# Face Mask Detection

## Expected Hardware
* [Raspberry Pi 4 4GB with a case](https://www.canakit.com/raspberry-pi-4-4gb.html)
* [5MP OV5647 PiCamera from Arducam](https://www.arducam.com/docs/cameras-for-raspberry-pi/native-raspberry-pi-cameras/5mp-ov5647-cameras/)

## Getting Started
* Setup the Raspberry Pi case and Operating System by following the Getting Started section on page 3 at `documentation/CanaKit-Raspberry-Pi-Quick-Start-Guide-4.0.pdf` or https://www.canakit.com/Media/CanaKit-Raspberry-Pi-Quick-Start-Guide-4.0.pdf
  * With NOOBS, use the recommended operating system
* Setup the PiCamera
  * Assemble the PiCamera case from Arducam using `documentation/Arducam-Case-Setup.pdf` or https://www.arducam.com/docs/cameras-for-raspberry-pi/native-raspberry-pi-cameras/5mp-ov5647-cameras/
  * [Attach your PiCamera module to the Raspberry Pi and enable the camera](https://projects.raspberrypi.org/en/projects/getting-started-with-picamera/2)

## New requirements.txt

```
keras==2.3.1
imutils==0.5.3
numpy==1.18.2
opencv-python==4.2.0.*
matplotlib==3.2.1
argparse==1.1
scipy==1.4.1
scikit-learn==0.23.1
pillow==7.2.0
streamlit==0.65.2
playsound
pyobjc
```

## Raspberry Pi App Installation & Execution

> Run these commands after cloning the project

| Commands                                                                                                                     | Time to completion |
|------------------------------------------------------------------------------------------------------------------------------|--------------------|
| sudo apt install -y libatlas-base-dev liblapacke-dev gfortran                                                                | 1min               |
| sudo apt install -y libhdf5-dev libhdf5-103                                                                                  | 1min               |
| pip3 install -r requirements.txt                                                                                             | 1-3 mins           |
| wget "https://raw.githubusercontent.com/PINTO0309/Tensorflow-bin/master/tensorflow-2.4.0-cp37-none-linux_armv7l_download.sh" | less than 10 secs  |
| ./tensorflow-2.4.0-cp37-none-linux_armv7l_download.sh                                                                        | less than 10 secs  |
| pip3 install tensorflow-2.4.0-cp37-none-linux_armv7l.whl                                                                     | 1-3 mins           |

**Comment by vinamramunot-tech** [comment]
I have tested this on Raspberry Pi and it runs perfectly for me. Please test on your side and let me know if you face any issues. I would be happy to work on it 😃 fix issues.

**Comment by chandrikadeb7** [comment]
> @chandrikadeb7 I have tested this on Raspberry Pi and it runs perfectly for me. Please test on your side and let me know if you face any issues. I would be happy to work on it 😃 fix issues.

Hi, if still possible can you raise a PR with an updated requirements file. Thanks.

**Comment by vinamramunot-tech** [comment]
will do! thank you for giving me the opportunity.

**Comment by vinamramunot-tech** [comment]
@chandrikadeb7 I do want to highlight that this is fix for raspberry pi and not for any other machine. #44 error shouldn't appear on a computer with the latest TensorFlow. Do you still want me to create a PR?

**Comment by chandrikadeb7** [comment]
> #44

Yes, please create a PR for this.

**Comment by TheBlackfurGuy** [comment]
I ran into multiple issues while using a raspi 4 4GB. While running everything as documented above the first issue arises because opencv is only available in 4.1.0.* and 4.3.0.* I kind of fixed it by just using 4.3.0.* The next issue is the following:
```
Collecting pyobjc-framework-ScreenSaver==7.1 (from pyobjc->-r requirements.txt (line 12))
  Downloading https://files.pythonhosted.org/packages/eb/95/9bc53622bc8f09211459c9ac55651d04dd6da5cdb307248f770be2919d82/pyobjc-framework-ScreenSaver-7.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9bj_in5_/pyobjc-framework-ScreenSaver/setup.py", line 23, in <module>
        py_limited_api=True,
      File "/tmp/pip-install-9bj_in5_/pyobjc-framework-ScreenSaver/pyobjc_setup.py", line 414, in Extension
        os_level = get_os_level()
      File "/tmp/pip-install-9bj_in5_/pyobjc-framework-ScreenSaver/pyobjc_setup.py", line 200, in get_os_level
        with open("/System/Library/CoreServices/SystemVersion.plist", "rb") as fp:
    FileNotFoundError: [Errno 2] No such file or directory: '/System/Library/CoreServices/SystemVersion.plist'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-9bj_in5_/pyobjc-framework-ScreenSaver/
```
I have no idea what that means. Why is it downloading a screensaver framework?

**Comment by chandrikadeb7** [comment]
> I ran into multiple issues while using a raspi 4 4GB. While running everything as documented above the first issue arises because opencv is only available in 4.1.0.* and 4.3.0.* I kind of fixed it by just using 4.3.0.* The next issue is the following:
> 
> ```
> Collecting pyobjc-framework-ScreenSaver==7.1 (from pyobjc->-r requirements.txt (line 12))
>   Downloading https://files.pythonhosted.org/packages/eb/95/9bc53622bc8f09211459c9ac55651d04dd6da5cdb307248f770be2919d82/pyobjc-framework-ScreenSaver-7.1.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-9bj_in5_/pyobjc-framework-ScreenSaver/setup.py", line 23, in <module>
>         py_limited_api=True,
>       File "/tmp/pip-install-9bj_in5_/pyobjc-framework-ScreenSaver/pyobjc_setup.py", line 414, in Extension
>         os_level = get_os_level()
>       File "/tmp/pip-install-9bj_in5_/pyobjc-framework-ScreenSaver/pyobjc_setup.py", line 200, in get_os_level
>         with open("/System/Library/CoreServices/SystemVersion.plist", "rb") as fp:
>     FileNotFoundError: [Errno 2] No such file or directory: '/System/Library/CoreServices/SystemVersion.plist'
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-9bj_in5_/pyobjc-framework-ScreenSaver/
> ```
> 
> I have no idea what that means. Why is it downloading a screensaver framework?

Please use the latest committed code. The pyobjc module is removed.

**Comment by TheBlackfurGuy** [comment]
Thanks for your reply, if I use the latest committed code I get the issue that was fixed with new requirements.txt

**Comment by vinamramunot-tech** [comment]
@chandrikadeb7 I have started a PR #126. I am not sure why one of the checks didn't complete. Please let me know if there are any changes required.

**Comment by vinamramunot-tech** [comment]
@chandrikadeb7 This issue should be fixed
