### ISSUE TITLE
Cannot reproduce your result

### ISSUE THREAD

**Issue by heathcliffYang** [chandrikadeb7/Face-Mask-Detection#119]
## 🐛 Bug Report

I run detect_mask_image.py and feed the same image as yours but I get different predictions.
The model I used is mask_detector.model you provided. 
![output](https://user-images.githubusercontent.com/22412607/108495559-e7617a80-72e3-11eb-9d62-32791c6929d8.jpg)

Thank you!

**Comment by chandrikadeb7** [comment]
> ## 🐛 Bug Report
> I run detect_mask_image.py and feed the same image as yours but I get different predictions.
> The model I used is mask_detector.model you provided.
> ![output](https://user-images.githubusercontent.com/22412607/108495559-e7617a80-72e3-11eb-9d62-32791c6929d8.jpg)
> 
> Thank you!

I'm able to get the result perfectly. Please train the dataset and follow the setup instructions.
