### ISSUE TITLE
Collect more dataset samples of real with_mask images

### ISSUE THREAD

**Issue by chandrikadeb7** [chandrikadeb7/Face-Mask-Detection#12]
The images must not be duplicate of the current dataset

**Comment by Liuqiyuan670** [comment]
thanks for your share,but the link to download dataset doesn't work,can you share the dataset in another way?

**Comment by akshay-dct** [comment]
@Liuqiyuan670 what do you mean by it doesn't work, could you elaborate any issue rising up?
