### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by muthuannamalai12** [chandrikadeb7/Face-Mask-Detection#120]
When Running the GitHub action to auto-assign Mentors for every PR it displays a [warning]Resource not accessible by integration` when running against PRs and it does not auto-assign reviewers. Similar to the issue link given below👇
kentaro-m/auto-assign-action#29

**Comment by muthuannamalai12** [comment]
@chandrikadeb7  I would to work and correct it. Kindly assign me this issue as a part of DWOC.

**Comment by chandrikadeb7** [comment]
Similar issue #111
