### ISSUE TITLE
 module 'streamlit' has no attribute 'beta_set_page_config'

### ISSUE THREAD

**Issue by MdAkdas** [chandrikadeb7/Face-Mask-Detection#144]
## 🐛 Bug Report

beta_set_page_config has been renamed to set_page_config.
https://github.com/streamlit/streamlit/issues/2251#issuecomment-780713739

![image](https://user-images.githubusercontent.com/43089126/132713879-5eb0bcd9-ba8c-465b-953d-01ac90ea0dcc.png)

**Comment by sreyan-ghosh** [comment]
Hi, I have made a PR that solves this issue. Please consider it as my submission towards Hacktoberfest2021. Cheers.
