### ISSUE TITLE
windows 10 installation

### ISSUE THREAD

**Issue by acemi1** [chandrikadeb7/Face-Mask-Detection#163]
windows installation
I could not run virtualenv in windows operating system.
Is there an installation guide to run the program in windows operating system?

source : The term 'source' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
 the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1

**Comment by chandrikadeb7** [comment]
> windows installation I could not run virtualenv in windows operating system. Is there an installation guide to run the program in windows operating system?
> 
> source : The term 'source' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. At line:1 char:1

https://github.com/chandrikadeb7/Face-Mask-Detection/blob/master/Windows_guide.md
