### ISSUE TITLE
EdgeTPU compatible model (Google Coral)

### ISSUE THREAD

**Issue by geekzain** [chandrikadeb7/Face-Mask-Detection#2]
Hey there, good work ! Do you have the model that is compatible with the Coral?

**Comment by chandrikadeb7** [comment]
> Hey there, good work ! Do you have the model that is compatible with the Coral?

https://github.com/chandrikadeb7/Face-Mask-Detection/blob/master/mask_detector.model

**Comment by geekzain** [comment]
> > Hey there, good work ! Do you have the model that is compatible with the Coral?
> 
> https://github.com/chandrikadeb7/Face-Mask-Detection/blob/master/mask_detector.model

That's for the mask detection, but the face detection is still done by a caffee model. (There's a face detection model provided by coral, but that problem with that is when someone has a mask on, it doesn't detect the face, which means you woun't be able to see the coordinates.)

**Comment by chandrikadeb7** [comment]
> > > Hey there, good work ! Do you have the model that is compatible with the Coral?
> > 
> > 
> > https://github.com/chandrikadeb7/Face-Mask-Detection/blob/master/mask_detector.model
> 
> That's for the mask detection, but the face detection is still done by a caffee model. (There's a face detection model provided by coral, but that problem with that is when someone has a mask on, it doesn't detect the face, which means you woun't be able to see the coordinates.)

Yes, the Coral model is not implemented.
