### ISSUE TITLE
Collect images of coloured masked faces

### ISSUE THREAD

**Issue by chandrikadeb7** [chandrikadeb7/Face-Mask-Detection#21]
Please collect more images of black or coloured masked faces to be included in the dataset.

**Comment by sandheepp** [comment]
Any updates on coloured masks?

**Comment by chandrikadeb7** [comment]
> Any updates on coloured masks?

Not yet

**Comment by khushibalyan220101** [comment]
Can i add coloured masks photos in the images folder..
