### ISSUE TITLE
Face with Beard

### ISSUE THREAD

**Issue by AsadFarooq5777** [chandrikadeb7/Face-Mask-Detection#29]
In case of beard algorithm predict face with Mask but there is no mask on face

**Comment by AmmarRashed** [comment]
I suppose you could add more faces with beards in the "without_mask" folder. That should help the model distinguish better between a beard and a mask.
An example dataset:
https://github.com/Keshav-Aggarwal/Beard-Face-Dataset/blob/master/Beard%20Dataset.zip
There is also faces in disguise dataset:
https://neurohive.io/en/datasets/disguised-face-recognition/

**Comment by chandrikadeb7** [comment]
Closing issue as adding more dataset will solve the problem.
