### ISSUE TITLE
Not all images are able to process

### ISSUE THREAD

**Issue by jforjay1** [chandrikadeb7/Face-Mask-Detection#33]
if I process the below image it gives an error of Assertion failed in OpenCV.

Error:
File "detect_mask_image.py", line 105, in <module>
    mask_image()
  File "detect_mask_image.py", line 76, in mask_image
    face = cv2.cvtColor(face, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

If you encounter this error you need to manually delete "./images/out.jpg" and save another image which can be processed e.g. "./images/pic2.jpg" as "./images/out.jpg".

![pic5](https://user-images.githubusercontent.com/46365760/92987281-b54f1f80-f4de-11ea-946e-dee274ea21fa.jpg)

**Comment by Shubhamsm** [comment]
[https://github.com/ageitgey/face_recognition/issues/933](url)
you can check the same issue here. Image is not loading in this case.

**Comment by shelyavic** [comment]
The link doesn't work

**Comment by shelyavic** [comment]
Couldn't find the solution in that thread
