### ISSUE TITLE
video stops frequently with error (-215:Assertion failed) !_src.empty() in function 'cvtColor'

### ISSUE THREAD

**Issue by nishanttyagi** [chandrikadeb7/Face-Mask-Detection#36]
How can I use IP camera for streaming and video stops frequently with following error.

Traceback (most recent call last):
  File "detect_mask_video.py", line 116, in <module>
    (locs, preds) = detect_and_predict_mask(frame, faceNet, maskNet)
  File "detect_mask_video.py", line 55, in detect_and_predict_mask
    face = cv2.cvtColor(face, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.2.0) /Users/travis/build/skvark/opencv-python/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**Comment by shelyavic** [comment]
What's the solution?
