### ISSUE TITLE
Tensorflow-lite

### ISSUE THREAD

**Issue by Rich2020** [chandrikadeb7/Face-Mask-Detection#41]
Any way to get the `detect_mask_video.py` or `detect_mask_image.py` working with Tensorflow lite? I don't need to train the model - I just want to run it.

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/250_Face-Mask-Detection
https://github.com/PINTO0309/TensorflowLite-bin
https://github.com/PINTO0309/Tensorflow-bin
