### ISSUE TITLE
Improve the documentation by adding awards/achievements section

### ISSUE THREAD

**Issue by chandrikadeb7** [chandrikadeb7/Face-Mask-Detection#49]
Please share a defined layout for the Readme documentation of this repo. For the details to be added, I'll send the necessary images.

**Comment by anushka23g** [comment]
Hey, I would like to do it, kindly do assign me this issue.

**Comment by vilsi12** [comment]
can you assign me
this

**Comment by chandrikadeb7** [comment]
> can you assign me
> this

Sure! Attaching the resources here.

**Comment by anushka23g** [comment]
Hey, can you assign this to me too?

**Comment by chandrikadeb7** [comment]
> Hey, can you assign this to me too?

This issue is already assigned. If it remains inactive for more than 7 days, it will be assigned to you.

**Comment by anushka23g** [comment]
okay

**Comment by kritikashah20** [comment]
Hey, I am a participant of SWOC. I want to know is this issue under SWOC as well? If yes,  can you assign me this issue?
