### ISSUE TITLE
Add new entries for coloured masks in dataset folder

### ISSUE THREAD

**Issue by chandrikadeb7** [chandrikadeb7/Face-Mask-Detection#51]

**Comment by keshav340** [comment]
Can  I do this

**Comment by vaishnavi-1** [comment]
I can do this, assign it to me.

**Comment by chandrikadeb7** [comment]
@keshav340 @vaishnavi-1 Please mention the different colours that you want to add for the masks dataset. Also the number of images.

**Comment by vaishnavi-1** [comment]
@chandrikadeb7 I can add 50-60 images of yellow and 50-60 images of red coloured masks.

**Comment by keshav340** [comment]
I can add  150-200 images of green, red, yellow, and mixed colored masks.

**Comment by chandrikadeb7** [comment]
> @chandrikadeb7 I can add 100-120 images of yellow, pink, red coloured masks each.

You can proceed!

**Comment by chandrikadeb7** [comment]
> I can add 150-200 images of green, red, yellow, orange, and mixed colored masks.

Proceed with exceptions to @vaishnavi-1 's colours choices.

**Comment by Abhinav-B-19** [comment]
Can I solve this issue. I can add 150 -200 images of blue, pink, black and brown colored masks
