### ISSUE TITLE
Alarm system when "No Mask" detected

### ISSUE THREAD

**Issue by chandrikadeb7** [chandrikadeb7/Face-Mask-Detection#52]
Implement an alarming system when the camera detects "No Mask" in real-time video streams.

**Comment by Adityanagraj** [comment]
In  this alarm system we have to use any IOT system or any ALERT message with audio enabled is fine !!!

**Comment by chandrikadeb7** [comment]
> In this alarm system we have to use any IOT system or any ALERT message with audio enabled is fine !!!

Alert with audio is alright!

**Comment by meenal2000** [comment]
Hey , 
Can you assign this issue to me ? I want to work on this . Thank you.

**Comment by ritikchinu** [comment]
Hey, i can solve this issue by raising an alert dialog with audio. So if you can assign it to me.
Thank you

**Comment by sahebsunny** [comment]
Mam, I worked on a very similar project with the alarm system,
Let me work on it

**Comment by Aayush-hub** [comment]
@chandrikadeb7Mam, I want to work on, can you please assign me this.

**Comment by chandrikadeb7** [comment]
@meenal2000 Are you still working on it?

**Comment by sahebsunny** [comment]
@chandrikadeb7 Mam If it's open please let me as I worked on a similar project and Implemented an Alarm system in it.

**Comment by meenal2000** [comment]
@chandrikadeb7 Hey, no . I have stopped working on it. You may assign to someone else.

**Comment by chandrikadeb7** [comment]
> Hey, i can solve this issue by raising an alert dialog with audio. So if you can assign it to me.
> Thank you

Assigning you @ritikchinu Proceed!

**Comment by ritikchinu** [comment]
hey please unassign this issue as I have already other issues assigned to me.

**Comment by chandrikadeb7** [comment]
@sahebsunny Proceed!
