### ISSUE TITLE
Display ratio / count of who have wore the mask out of persons recognised

### ISSUE THREAD

**Issue by Manikanta05** [chandrikadeb7/Face-Mask-Detection#54]
Displaying the total count/ratio of persons who have wore mask out of total count of persons recognised .

**Comment by Anu-MADMAX** [comment]
I'm interested . How can I get started

**Comment by chandrikadeb7** [comment]
@Manikanta05 @Anu-MADMAX please define a possible layout for this solution. After that I'll assign the issue and tags.

**Comment by Anu-MADMAX** [comment]
Hi! Thanks for assigning me this issue , I'm a beginner so could u help on
where i should begin?

**Comment by TanweerulHaque** [comment]
@chandrikadeb7 I know how to proceed with this issue. Can you assign me the same?? I am SWoC participant.
