### ISSUE TITLE
Create Code of Conduct. md

### ISSUE THREAD

**Issue by muthuannamalai12** [chandrikadeb7/Face-Mask-Detection#61]
Hi,
I found that this project repository is not having a code of conduct file in this repository, kindly assign me this issue and I would like to contribute a well-formatted code of conduct file as you know code of conduct is a necessary file which the contributors need to follow so that everyone follows a decorum.

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC. Kindly assign it to me

**Comment by chandrikadeb7** [comment]
@muthuannamalai12 you can proceed, thanks!

**Comment by muthuannamalai12** [comment]
I have created a pull request.Kindly review it
