### ISSUE TITLE
Create a help guide for running the project in Windows OS

### ISSUE THREAD

**Issue by chandrikadeb7** [chandrikadeb7/Face-Mask-Detection#66]
Documentation should include detailed steps including screenshots.

**Comment by M-PRERNA** [comment]
Hi there,
I am a SWOC participant, can you assign me this issue? I'll be making the PR once the Program begins, that is after 5th January.

**Comment by himanshu007-creator** [comment]
Mam, i am a participant in both swoc and dwoc. Please add SWOC and assign me this issue

**Comment by chandrikadeb7** [comment]
@M-PRERNA proceed!

**Comment by M-PRERNA** [comment]
okay ma'am
Do we have a slack channel for this project?

**Comment by chandrikadeb7** [comment]
> okay ma'am
> Do we have a slack channel for this project?

Yes. Please join.

**Comment by kritikaparmar-programmer** [comment]
@chandrikadeb7 I want to work on this issue.

**Comment by chandrikadeb7** [comment]
@kritikaparmar-programmer What's the progress?

**Comment by kritikaparmar-programmer** [comment]
Hey, @chandrikadeb7  will submit a pr today.
