### ISSUE TITLE
Add Contributors.md file

### ISSUE THREAD

**Issue by muthuannamalai12** [chandrikadeb7/Face-Mask-Detection#67]
Hai,
I would like to add Contributors.md file in your project in the form of a table and display a link to it in README.md

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC. Kindly assign it to me

**Comment by chandrikadeb7** [comment]
@muthuannamalai12 Go on!

**Comment by muthuannamalai12** [comment]
I have created a pull request.Kindly review it
