### ISSUE TITLE
Using inception v3  architecture to train the model{SWOC21}

### ISSUE THREAD

**Issue by spursbyte** [chandrikadeb7/Face-Mask-Detection#71]
Inception V3 can provide better accuracies to the model.So can you assign me this issue?

**Comment by chandrikadeb7** [comment]
@spursbyte You can proceed!

**Comment by TanweerulHaque** [comment]
Can you assign me the issue if it's still not done ??

**Comment by spursbyte** [comment]
It has been assigned to me .

**Comment by TanweerulHaque** [comment]
@chandrikadeb7 If it's still not done, can I proceed with it ??

**Comment by chandrikadeb7** [comment]
> It has been assigned to me .

What's the progress?

**Comment by spursbyte** [comment]
> > It has been assigned to me .
> 
> What's the progress?

Yes on it..delayed due to online sems. Started working already
