### ISSUE TITLE
Integrate welcome bot

### ISSUE THREAD

**Issue by muthuannamalai12** [chandrikadeb7/Face-Mask-Detection#72]
I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.
For reference, check out: https://github.com/apps/welcome

If you feel this is a great idea!
Please assign it to me.

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC. Kindly assign it to me

**Comment by chandrikadeb7** [comment]
@muthuannamalai12 You can proceed!

**Comment by muthuannamalai12** [comment]
I have created a pull request. Kindly review it
