### ISSUE TITLE
Update number of images in Dataset section of Readme

### ISSUE THREAD

**Issue by chandrikadeb7** [chandrikadeb7/Face-Mask-Detection#74]
Update the dataset section with present number of images in dataset folder of the repo.

**Comment by Abhinav-B-19** [comment]
Can you assign this issue to me. I am a SWOC participant.

**Comment by Sumanpal3108** [comment]
I want to work on this issue. Please assign it to me. I am a dwoc participant

**Comment by jatinjain001** [comment]
I would like to work on it

**Comment by chandrikadeb7** [comment]
> I would like to work on it

Proceed!

**Comment by jatinjain001** [comment]
Okay

**Comment by jatinjain001** [comment]
> > I would like to work on it
> 
>

**Comment by jatinjain001** [comment]
> > > I would like to work on it

>> Proceed
