### ISSUE TITLE
Insert Google Collab working link of this project in Readme

### ISSUE THREAD

**Issue by chandrikadeb7** [chandrikadeb7/Face-Mask-Detection#75]
- [ ] Integrate this project on Google Collab
- [ ] Include the project link along with mentioning the accuracy of the model in Readme file

**Comment by Purvanshsingh** [comment]
Please assign it to me for SWOC.

**Comment by Purvanshsingh** [comment]
@chandrikadeb7 Please correct me is I am wrong,
I have to create a collab notebook for train_mask_detector.py, right?

**Comment by chandrikadeb7** [comment]
> @chandrikadeb7 Please correct me if I am wrong,
> I have to create a collab notebook for train_mask_detector.py, right?

Yes

**Comment by Purvanshsingh** [comment]
okay, will do it.

**Comment by pavan2131** [comment]
Plz assign me

**Comment by Rahul555-droid** [comment]
Hi chandrika is there any other script that needs to be made into a notebook/colab ?

**Comment by chandrikadeb7** [comment]
> okay, will do it.

What's the progress?

**Comment by Purvanshsingh** [comment]
It's almost done Just having some doubts will ping you regarding that today.

**Comment by TanweerulHaque** [comment]
If there's no work done, I can complete it by today. I know how to do it. @chandrikadeb7 Kindly assign me this issue.

**Comment by TanweerulHaque** [comment]
@chandrikadeb7 If there's no work done, I can complete it by today. I know how to do it. Kindly assign me this issue.

**Comment by TanweerulHaque** [comment]
I have sent a PR @chandrikadeb7 Please review it.

**Comment by TanweerulHaque** [comment]
@chandrikadeb7 Please see to this.
