### ISSUE TITLE
Update Contributors.md file

### ISSUE THREAD

**Issue by chandrikadeb7** [chandrikadeb7/Face-Mask-Detection#77]
Update the file with new contributors with the help of some dependabot/action bots.

**Comment by muthuannamalai12** [comment]
Can I do it using this website https://contrib.rocks/preview which can auto generate contributor images just by giving the repository name

**Comment by muthuannamalai12** [comment]
The output will be like 
![Contributor](https://user-images.githubusercontent.com/64524822/103923677-64250480-513b-11eb-9311-cbcb6242c783.png)

**Comment by muthuannamalai12** [comment]
I f you like it I would love to work on this issue as a part of DWOC. Kindly assign it to me

**Comment by akrish4** [comment]
> Update the file with new contributors with the help of some dependabot/action bots.

Yes I can add a file for the same and add all contributors in it `CONTRIBUTORS.md` in a tabular format with their image and name in each table 
Kindly do assign me @chandrikadeb7

**Comment by chandrikadeb7** [comment]
> > Update the file with new contributors with the help of some dependabot/action bots.
> 
> Yes I can do it and add all contributors in it `CONTRIBUTORS.md` in a tabular format with their image and name in each table
> Kindly do assign me @chandrikadeb7

As a part of DWOC or SWOC?

**Comment by chandrikadeb7** [comment]
> If you like it I would love to work on this issue as a part of DWOC. Kindly assign it to me

Hi, just a request that others should also contribute.. will assign you after you complete the existing assigned issues :)

**Comment by akrish4** [comment]
> As a part of DWOC or SWOC?

both

**Comment by Amit366** [comment]
Is this issue open?? @chandrikadeb7

**Comment by chandrikadeb7** [comment]
> Is this issue open?? @chandrikadeb7

yes

**Comment by Amit366** [comment]
Is it like adding contributor's names to read me??

**Comment by chandrikadeb7** [comment]
@akrish4 What's the progress?

**Comment by chandrikadeb7** [comment]
> Is it like adding contributor's names to read me??

Yes to the file

**Comment by muthuannamalai12** [comment]
> > If you like it I would love to work on this issue as a part of DWOC. Kindly assign it to me
> 
> Hi, just a request that others should also contribute.. will assign you after you complete the existing assigned issues :)

I have completed the previous issue If you want I can do it

**Comment by Amit366** [comment]
@chandrikadeb7 please review the PR

**Comment by Amit366** [comment]
@chandrikadeb7 please review the PR.
