### ISSUE TITLE
Not Detecting Multiple Faces in Video

### ISSUE THREAD

**Issue by pavitrashah** [chandrikadeb7/Face-Mask-Detection#8]
When i tried to detect multiple faces while running the video version, it was only able to detect one face at a time. 
And when i ran the image version it was successfully able to detect multiple faces and tell whether they were wearing mask or not.
Can you tell me why this is happening? Because its suppose to detect multiple faces. And what could be it's solution.
It would be really great if you could help me on this.
Thanks

**Comment by pavitrashah** [comment]
Hey, so i actually found a solution for this issue. 

To fix this we have to remove `face = np.expand_dims(face, axis=0)` from Line 59 and add `faces = np.array(faces, dtype="float32")` & `preds = maskNet.predict(faces, batch_size=32)`  instead of Line 71 in that `if len(faces) > 0:` statement.

The issue was that the predict function is expecting an np array and instead of that we were serving it a list, and Line 59 `face = np.expand_dims(face, axis=0)` which we removed was just messing with the dimensions of the array.

**Comment by pavitrashah** [comment]
> When i tried to detect multiple faces while running the video version, it was only able to detect one face at a time.
> And when i ran the image version it was successfully able to detect multiple faces and tell whether they were wearing mask or not.
> Can you tell me why this is happening? Because its suppose to detect multiple faces. And what could be it's solution.
> It would be really great if you could help me on this.
> Thanks

Hey, so i actually found a solution for this issue.

To fix this we have to remove face = np.expand_dims(face, axis=0) from Line 59 and add faces = np.array(faces, dtype="float32") & preds = maskNet.predict(faces, batch_size=32) instead of Line 71 in that if len(faces) > 0: statement.

The issue was that the predict function is expecting an np array and instead of that we were serving it a list, and Line 59 face = np.expand_dims(face, axis=0) which we removed was just messing with the dimensions of the array.

**Comment by chandrikadeb7** [comment]
> > When i tried to detect multiple faces while running the video version, it was only able to detect one face at a time.
> > And when i ran the image version it was successfully able to detect multiple faces and tell whether they were wearing mask or not.
> > Can you tell me why this is happening? Because its suppose to detect multiple faces. And what could be it's solution.
> > It would be really great if you could help me on this.
> > Thanks
> 
> Hey, so i actually found a solution for this issue.
> 
> To fix this we have to remove `face = np.expand_dims(face, axis=0)` from Line 59 and add `faces = np.array(faces, dtype="float32")` & `preds = maskNet.predict(faces, batch_size=32)` instead of Line 71 in that `if len(faces) > 0:` statement.
> 
> The issue was that the predict function is expecting an np array and instead of that we were serving it a list, and Line 59 `face = np.expand_dims(face, axis=0)` which we removed was just messing with the dimensions of the array.

Please create a PR if its working.

**Comment by pavitrashah** [comment]
> > 
> > Hey, so i actually found a solution for this issue.
> > To fix this we have to remove `face = np.expand_dims(face, axis=0)` from Line 59 and add `faces = np.array(faces, dtype="float32")` & `preds = maskNet.predict(faces, batch_size=32)` instead of Line 71 in that `if len(faces) > 0:` statement.
> > The issue was that the predict function is expecting an np array and instead of that we were serving it a list, and Line 59 `face = np.expand_dims(face, axis=0)` which we removed was just messing with the dimensions of the array.
> 
> Please create a PR if its working.

I have created the PR so just review it and merge if its working for you. And let me know if still there are any issues.

**Comment by chandrikadeb7** [comment]
> > > Hey, so i actually found a solution for this issue.
> > > To fix this we have to remove `face = np.expand_dims(face, axis=0)` from Line 59 and add `faces = np.array(faces, dtype="float32")` & `preds = maskNet.predict(faces, batch_size=32)` instead of Line 71 in that `if len(faces) > 0:` statement.
> > > The issue was that the predict function is expecting an np array and instead of that we were serving it a list, and Line 59 `face = np.expand_dims(face, axis=0)` which we removed was just messing with the dimensions of the array.
> > 
> > 
> > Please create a PR if its working.
> 
> I have created the PR so just review it and merge if its working for you. And let me know if still there are any issues.

Works fine for me. Thanks!
