### ISSUE TITLE
How can I cite your work?

### ISSUE THREAD

**Issue by ltkhang** [chandrikadeb7/Face-Mask-Detection#84]
## 📚 Documentation

(A clear and concise description of what the issue is.)
Dear author,

I am going to use your dataset as a part of my work, so how can I cite your work?

I can't find any "citation" part in your README.

Hope to hear from you soon.

Best regards,

**Comment by chandrikadeb7** [comment]
> ## 📚 Documentation
> (A clear and concise description of what the issue is.)
> Dear author,
> 
> I am going to use your dataset as a part of my work, so how can I cite your work?
> 
> I can't find any "citation" part in your README.
> 
> Hope to hear from you soon.
> 
> Best regards,

Updating soon!

**Comment by chandrikadeb7** [comment]
> ## 📚 Documentation
> (A clear and concise description of what the issue is.)
> Dear author,
> 
> I am going to use your dataset as a part of my work, so how can I cite your work?
> 
> I can't find any "citation" part in your README.
> 
> Hope to hear from you soon.
> 
> Best regards,

Description is in Readme
