### ISSUE TITLE
Create a Citation Section in Readme file

### ISSUE THREAD

**Issue by chandrikadeb7** [chandrikadeb7/Face-Mask-Detection#86]
## 📚 Documentation

Draft a citation for other developers to use any part of this projec repo (code or dataset).

**Comment by Sobhit25** [comment]
Can, I take up this issue.

**Comment by Pranjal-2001** [comment]
Could you please assign it to me?

**Comment by chandrikadeb7** [comment]
> Can, I take up this issue.

What's the progress? If left undone in 7 days I'll pass the assignment to others.

**Comment by vilsi12** [comment]
Please assign to me

**Comment by Sobhit25** [comment]
Mam, I pressed the unassigne button by mistake,pl do assign me again.

**Comment by chandrikadeb7** [comment]
> Mam, I pressed the unassigne button by mistake,pl do assign me again.

Please make the PR soon, it's urgent for this issue.
