### ISSUE TITLE
PR TEMPLATE

### ISSUE THREAD

**Issue by muthuannamalai12** [chandrikadeb7/Face-Mask-Detection#90]
## 🚀 Feature
I can add a pr template , which will have few checklists and options like uploading screenshots and describing about the pr etc , which will give better understanding of pr for the maintainer
(A clear and concise description of what the feature is.)

## Motivation
Self Motivation
(Please outline the motivation for the proposal.)

## Pitch
This is a great feature like issue template in this project , this will give a better idea about the pr and also make the work easy
(Please explain why this feature should be implemented and how it would be used.)

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC. Kindly assign it to me

**Comment by chandrikadeb7** [comment]
> I would love to work on this issue as a part of DWOC. Kindly assign it to me

Proceed!

**Comment by muthuannamalai12** [comment]
I have created a pull request. Kindly review it
