### ISSUE TITLE
Add Contributors Table in README.md

### ISSUE THREAD

**Issue by samir-0711** [chandrikadeb7/Face-Mask-Detection#92]
## 📚 Documentation

To make README.md file beautiful and give credit to contributors
Like this
![image](https://user-images.githubusercontent.com/68433936/104682288-53b3f180-571a-11eb-89e0-7162eaf98b46.png)

**Comment by samir-0711** [comment]
I would like to work on this.

**Comment by chandrikadeb7** [comment]
Duplicate of issue #77
