### ISSUE TITLE
Adding a contributor's table in ReadMe

### ISSUE THREAD

**Issue by shatakshisingh24** [chandrikadeb7/Face-Mask-Detection#97]
I can add a contributor's table in Readme file, like this one.

![image](https://user-images.githubusercontent.com/51313537/104820300-dabbb380-5859-11eb-9114-6fb883849d86.png)

Kindly assign me this issue, with label DWOC and Level-1 or 2

**Comment by Amit366** [comment]
Is this issue open??

**Comment by chandrikadeb7** [comment]
@shatakshisingh24 What's the progress?
